version: '3.6'

services:
  db:
    image: postgres:10.1-alpine

  web:
    build: .
    volumes:
      - ./chicode:/chicode/chicode
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
